require_relative '../../node_modules/@jigra/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def jigra_pods
  pod 'Jigra', :path => '../../node_modules/@jigra/ios'
  pod 'JigraCordova', :path => '../../node_modules/@jigra/ios'
end

target 'App' do
  jigra_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
