name: Attach .xcframework file to release

on: workflow_dispatch
jobs:
  publish-xcframework:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_14.2.app
      - run: brew install ghr
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: NPM ^9.5.0
        run: npm i -g npm@^9.5.0 --registry=https://registry.npmjs.org
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: native-publish
      - name: Build Jigra.xcframework
        run: carthage build --no-skip-current --use-xcframeworks
      - name: Build JigraCordova.xcframework
        run: |
          cd ios/JigraCordova
          xcodebuild archive -scheme Cordova -sdk iphonesimulator SKIP_INSTALL=NO -archivePath Build/iOS-Simulator
          xcodebuild archive -scheme Cordova -sdk iphoneos SKIP_INSTALL=NO -archivePath Build/iOS
          xcodebuild -create-xcframework -framework Build/iOS.xcarchive/Products/Library/Frameworks/Cordova.framework -framework Build/iOS-Simulator.xcarchive/Products/Library/Frameworks/Cordova.framework -output JigraCordova.xcframework
          cd ../..
      - name: Create Jigra.xcframework.zip
        run: |
          mkdir Carthage/Build/JigraCordova.xcframework
          mv ios/JigraCordova/JigraCordova.xcframework/* Carthage/Build/JigraCordova.xcframework
          zip -r Jigra.xcframework.zip Carthage/Build
          rm -rf ios/JigraCordova/JigraCordova.xcframework
      - name: Attach ZIP to latest release
        run: ghr -t ${{ secrets.GITHUB_TOKEN }} -replace $(git describe --tags --abbrev=0) Jigra.xcframework.zip
