name: Publish Native Android Library

on:
  workflow_call:
    secrets:
      ANDROID_TOKEN:
        required: true
      JIG_GH_RELEASE_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  publish-android:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: '5.x'
          token: ${{ secrets.JIG_GH_RELEASE_TOKEN }}
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew
      - name: Grant execute permission for publishing script
        run: chmod +x ./scripts/publish-android.sh
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Setup Jigra version
        working-directory: ./scripts
        env:
          ANDROID_TOKEN: ${{ secrets.ANDROID_TOKEN }}
        run: ./publish-android.sh
      - name: Publish package
        uses: gradle/gradle-build-action@v3
        with:
          arguments: publish-android
        env:
          GITHUB_TOKEN: ${{ secrets.ANDROID_TOKEN }}
